name: deepsdf
channels:
  - pytorch3d
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.3
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - fvcore=0.1.5.post20221221
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - iopath=0.1.9
  - ipydatawidgets=4.3.2
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.16.0
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - meshplot=0.4.0
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1s
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - portalocker=2.3.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pythreejs=2.4.2
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pytorch3d=0.7.4
  - pyyaml=6.0
  - pyzmq=23.2.0
  - readline=8.2
  - requests=2.28.1
  - send2trash=1.8.0
  - setuptools=65.6.3
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tabulate=0.8.10
  - termcolor=2.1.0
  - terminado=0.17.1
  - testpath=0.6.0
  - tk=8.6.12
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - traittypes=0.2.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022a
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.10
  - yacs=0.1.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - cachetools==5.3.1
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.0
      - imageio==2.31.1
      - lazy-loader==0.3
      - markdown==3.4.3
      - markupsafe==2.1.3
      - networkx==3.1
      - oauthlib==3.2.2
      - packaging==23.1
      - plotly==5.15.0
      - point-cloud-utils==0.29.6
      - protobuf==4.23.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybullet==3.2.5
      - pywavelets==1.4.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.21.0
      - scipy==1.11.1
      - tenacity==8.2.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tifffile==2023.7.10
      - trimesh==3.22.4
      - werkzeug==2.3.6